# Generated by Django 4.1.4 on 2023-04-02 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_quiz_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='givenquizquestions',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='givenquizquestions',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
    ]
