# Generated by Django 4.1.4 on 2023-04-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_givenquizquestions_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
